### ISSUE TITLE
Send custom tags with PRIVMSG

### ISSUE THREAD

**Issue by LosFarmosCTL** [MahdiBM/TwitchIRC#3]
Is it possible to add custom tags to outgoing PRIVMSGs? There is the `messageIdToReply` argument, but I'd specifically want to send a custom `client-nonce` to verify messages being sent successfully.

I can't see an option to add any additional tags, afaik `client-once` is the only one that even affects anything when sent to TMI, but it would be nice to have either a way of sending that specifically or an option for completely custom tags (`IncomingMessage` already contains the client-nonce tag).

**Comment by MahdiBM** [comment]
Twitch documentation doesn't mention sending any client-nonces through PRIVMSGs: https://dev.twitch.tv/docs/irc/tags/#privmsg-tags
I'm not sure if that'll be valid. Have you seen this somewhere so I can refer to it, or were you just wondering?!

**Comment by MahdiBM** [comment]
Someone in Twitch Dev Discord server did say you can send a client nonce... i can't confirm or deny since i'm on holiday for a week or two.

https://discord.com/channels/504015559252377601/523676013494796288/1089671374932561941

**Comment by LosFarmosCTL** [comment]
Yeah, Twitch does not have anything about it in their docs, but you can definitely send them, i.e. this is what the default webchat will send:

![image](https://user-images.githubusercontent.com/80157503/228000875-4dae8f19-1480-4b39-9e1c-d6ad393a8536.png)

No idea what Twitch uses it for, since they are not doing anything with the received tag client-side, but considering that i.e. the Twitch recap for whatever reason only counts emotes sent over webchat for their stats, they might do something with it on the backend.

But you can also send completely custom `client-nonce` tags and Twitch will pass them along, which in theory i.e. by including a UUID etc. makes it possible to confirm that your message actually got sent and wasn't silently dropped by Twitch (which is something that the webchat does not show, i.e. if you are shadowbanned or they are just not letting all messages through in very fast chats):

![image](https://user-images.githubusercontent.com/80157503/228002180-aa436e07-2e68-4c78-ab1e-bec33eed829a.png)

The nonce-tag will even be present on the resulting USERSTATE you receive back from Twitch:

![image](https://user-images.githubusercontent.com/80157503/228004103-7ba5f919-b96e-40ef-ac68-583e7f284daa.png)

There is also a `sent-ts` tag, I wasn't on Twitch when that was a thing they used for 1st party products and it does not seem to have any practical use case anymore, but it's also passed along to any message receiver:

![image](https://user-images.githubusercontent.com/80157503/228004981-16ab9ed4-d3a2-4e67-848e-73cf47ff3085.png)
(I did not know about the `sent-ts` tag originally, source is mm's honestly amazing [attempt at documenting some of Twitch's 3rd party garbage](https://git.kotmisia.pl/Mm2PL/docs/src/branch/master/irc.md#tags-on-outgoing-privmsgs))

**Comment by MahdiBM** [comment]
@LosFarmosCTL Does the new PR solve this? The changes are available in the `outgoing-prvmsg-client-nonce` branch.
I haven't tested it in real world but i'm confident it should be good enough 🤔

**Comment by LosFarmosCTL** [comment]
> Does the new PR solve this? 

LGTM on first sight, I can go ahead and test it properly in a few hours, but as long as the test is successful that looks like the correct IRC message.

**Comment by LosFarmosCTL** [comment]
Sorry, I had absolutely no time, i guess it's merged now anyways but I can confirm that everything works correctly.
